dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "pypy3"
install:
  - pip install coveralls coverage
  - pip install -r requirements.txt
script:
  - coverage run manage.py test posts --failfast --settings=blog.settings.test && coverage report
after_success:
  coveralls
env:
  - DJANGO_SETTINGS_MODULE=blog.settings.test
