version: '3'

services:

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=blog.settings.prod
    command: ./web/run.sh
    volumes:
      - .:/code
    ports:
      - "3000:8008"

  nginx:
    build: ./nginx
    ports:
      - "8001:8001"
    depends_on:
      - web
    links:
      - web
