from .base import *

# Disable debugging
DEBUG = False
TEMPLATE_DEBUG = False

ALLOWED_HOSTS = ['*']

STATIC_ROOT = "/var/www/example.com/static/"

SECURE_HSTS_SECONDS = 3600
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_PRELOAD = True
